### PR TITLE
some turkish encoding issues fixed.

### PR DESCRIPTION
**Pull request by berkaey**
I don't know if this is the best approach but fixes the problem. I tested with en, de, tr so far so good.
The last fixed I sent only worked with if the lang is "en" and also page contains turkish strings but if you change the lang to "tr", turkish chars. won't be encoded correctly.

### CODE REVIEW

**Comment by jonursenbach** [comment]
Is it possible to write a unit test for this?

**Comment by berkaey** [comment]
actually Im not good with writing tests and even if I do It will be hard to match if there is a abnormal characters.

**Comment by jonursenbach** [comment]
k. i'll take your word that this works. :p

**Comment by jonursenbach** [comment]
Tagged to 1.7.0

**Pull request merged**
